# List of organizations to query for full picture of steel-industry lobbying. Company names
# were gleaned from other LDA disclosures and from a web search to find major players in the steel
# industry.
# because the LDA API doesn't handle advanced text searching for client_name, these are
# handed to the API sequentially, one at a time.
organization_list:
- YALE UNIVERSITY
- WESTERN MICHIGAN UNIVERSITY
- VANDERBILT UNIVERSITY
- UNIVERSITY OF TEXAS
- UNIVERSITY OF PITTSBURGH
- UNIVERSITY OF NORTHERN IOWA
- UNIVERSITY OF MICHIGAN
- UNIVERSITY OF KENTUCKY
- UNIVERSITY OF ILLINOIS
- UNIVERSITY OF CALIFORNIA
- RICE UNIVERSITY
- OHIO UNIVERSITY
- NEW MEXICO STATE UNIVERSITY
- MASSACHUSETTS INSTITUTE OF TECHNOLOGY
- IOWA STATE UNIVERSITY
- GEORGIA INSTITUTE OF TECHNOLOGY
- GEORGIA TECH
- CARNEGIE MELLON
- CALIFORNIA INSTITUTE
- ARIZONA STATE UNIVERSITY
- HARVARD UNIVERSITY
- PRINCETON UNIVERSITY
- COLUMBIA UNIVERSITY
- AMERICAN UNIVERSITY
- STANFORD UNIVERSITY
