# List of organization names to send to LDA API query in order to estimate the full
# amount of lobbying done by these organizations (not just for CCS) over the period of
# lobbying disclosures. Note that this file used to be called 'search_terms_oil_and_gas_orgs.yml';
# however, because some of these are chemical companies and/or power/utility companies and/or
# trade associations, I changed the name.
# because the LDA API doesn't handle advanced text searching for client_name, these are
# handed to the API sequentially, one at a time.
organization_list:
- EXXON
- EXXONMOBIL
- OXY
- BRITISH PETROLEUM
- CHEVRON
- AMERICAN PETROLEUM INSTITUTE
- AMERICAN EXPLORATION & PRODUCTION COUNCIL
- AMERICAN EXPLORATION AND PRODUCTION COUNCIL
- AMERICAN GAS ASSOCIATION
- NATURAL GAS ALLIANCE
- ANADARKO PETROLEUM
- KERR MCGEE
- BAKKEN ENERGY
- BP AMERICA
- CALIFORNIA INDEPENDENT PETROLEUM ASSOCIATION
- CHESAPEAKE ENERGY
- CHINOOK
- NEXEN
- CNX RESOURCES
- CONCHO RESOURCES
- CONOCOPHILLIPS
- CORE ENERGY
- DEVON ENERGY
- DIFFERENTIATED GAS COORDINATING COUNCIL
- ENERGY MARKETERS OF AMERICA
- ENI US
- EOG RESOURCES
- EQT CORPORATION
- EQUINOR
- DENBURY
- GLENROCK PETROLEUM
- HYPERION RESOURCES INC
- IN SITU OIL SANDS ALLIANCE
- INDEPENDENT PETROLEUM ASSOCIATION
- KAUFFMAN COMPANY
- ANDEAVOR
- MARATHON OIL
- MARATHON PETROLEUM
- TESORO
- NATIONAL OCEAN INDUSTRIES ASSOCIATION
- NATURAL GAS SUPPLY
- SANDRIDGE ENERGY
- SHELL
- TOTALENERGIES
- WOODSIDE ENERGY
- PIONEER NATURAL RESOURCES
- PERMIAN
- TEXACO
- HESS CORPORATION
- XTO
- HESS CORP
- HESS CORP.
- ANDEAVOR
- NOBLE ENERGY
- MAERSK OIL
- WPX ENERGY
- PETROHAWK
- BG GROUP
- SOUTHERN COMPANY
- OCCIDENTAL
- KERR-MCGEE
- ANADARKO
- KERR MCGEE
- PETROLEUM
- ESSO
- IMPERIAL OIL
- MOBIL
- "EDISON ELECTRIC INSTITUTE"
- "AMERICAN ELECTRIC POWER"
- "DUKE ENERGY"
- "PROGRESS ENERGY"
- CINERGY
- "BP AMERICA"
- "CHAMBER OF COMMERCE"
- CALPINE
- "PACIFIC GAS & ELECTRIC"
- "PACIFIC GAS AND ELECTRIC"
- "PEABODY INVESTMENTS"
- "PEABODY ENERGY"
- TRANSCANADA
- "TC ENERGY"
- "CONOCO-PHILLIPS"
- "AIR PRODUCTS AND CHEMICALS"
- "AIR PRODUCTS & CHEMICALS"
- NRECA
- "NATIONAL RURAL ELECTRIC COOPERATIVE"
- HONEYWELL
- "PHILLIPS 66"
- "AMERICAN CHEMISTRY COUNCIL"
- "KOCH"
- "POET"
- "SEMPRA"
- "AIR LIQUIDE"
- "FLINT HILLS"
- "GEORGIA PACIFIC"
- "GEORGIAPACIFIC"
- "GEORGIA-PACIFIC"
- "MOLEX"
- "ENOVA"
- "SOUTHERN CALIFORNIA GAS"
- "SOCALGAS"
- "PACIFIC ENTERPRISES"
- "SAN DIEGO GAS"
- " CCS "
- "CARBON CAPTURE"
- "CARBON SEQUESTRATION"
- " CCUS "
- "CO2 CAPTURE"
- "NATIONAL GRID"
- "ENBRIDGE"
- "WILLIAMS COMPANIES"
- INVISIA
