authentication_endpoint: https://lda.senate.gov/api/auth/login/
chunk_size: 30
description_replace_dict_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/bill_abbreviations.yml
entity_endpoint: https://lda.senate.gov/api/v1/constants/filing/governmententities/
filings_endpoint: https://lda.senate.gov/api/v1/filings/
lda_apikey: b6c22528b6697dc3bf1fbf9ff5200d28d9991889
lda_username: lindseyegulden
lobbyist_filename_prefix: ccs_lda_lobbyists_terms
output_filename_prefix: ccs_lda_filings_terms
search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_for_categorization.yml
law_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/ccs_laws.yml
organization_name_handling_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/organization_name_handling.yml
sector_description_file: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/sector_descriptions.yml
company_name_replacements: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/company_name_replacements.yml
clean_client_description_col: clean_client_general_description
company_rename_col: client_rename
company_sector_assignments: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/sectors_updated.yml
path_to_lumped_sector_info: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/lumped_sectors.yml
political_party_congress_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/party_control_congress.yml
remove_org_key:
  - remove these organizations
  - keep
groupby_columns:
  - filing_year
  - filing_period
  - client_id
  - registrant_id
  - activity_id
core_ff_sectors:
  - oil and gas
  - investor owned utilities
  - chemicals, refining, and plastics
  - coal
  - energy technology
  - ccs
  - independent power producers
  - pipelines
  - municipal and cooperative utilities
  - oilfield services
  - clean hydrogen
ff_adjacent_sectors:
  - oil and gas
  - investor owned utilities
  - chemicals, refining, and plastics
  - coal
  - energy technology
  - ccs
  - independent power producers
  - air transit
  - railway
  - pipelines
  - municipal and cooperative utilities
  - business advocacy
  - fuel cell
  - land transit
  - oilfield services
  - carbon
  - clean hydrogen
subset_and_order_of_writeout_columns: # does not include entity binary column names: programmatically added to end
  - filing_uuid
  - total_number_lobbying_activities
  - total_number_of_lobbyists_on_filing
  - activity_id
  - n_lobbyists_for_activity
  - filing_year
  - filing_period
  - filing_dt_posted
  - which_congress
  - party_controlling_house
  - party_controlling_senate
  - party_controlling_white_house
  - filing_type
  - client_id
  - client_rename
  - client_name
  - client_general_description
  - sector
  - lumped_sector
  - very_lumped_sector
  - registrant_id
  - who_is_lobbying
  - dollars_spent_lobbying
  - lobbying_activity_usd
  - n_entities_lobbied
  - legistlative_entities_lobbied
  - executive_entities_lobbied
  - affiliated_organizations_present
  - very_likely_ccs
  - likely_ccs
  - potentially_ccs
  - general_issue_code
  - description
  - posted_by_name
  - registrant_name
  - registrant_contact_name
  - client_state
  - client_ppb_state
  - client_country
  - client_ppb_country
  - url
  - entity_expanded
  - clean_description
  - clean_client_general_description
  - contains_ccs_description
  - ccs_company
  - ccs_bills
  - bill_contains_some_ccs
  - not_ccs
  - terms_probably_ccs
  - terms_maybe_ccs
  - leaning_ccs
