authentication_endpoint: https://lda.senate.gov/api/auth/login/
chunk_size: 30
description_replace_dict_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/bill_abbreviations.yml
entity_endpoint: https://lda.senate.gov/api/v1/constants/filing/governmententities/
filings_endpoint: https://lda.senate.gov/api/v1/filings/
lda_apikey: b6c22528b6697dc3bf1fbf9ff5200d28d9991889
lda_username: lindseyegulden
query_param: filing_specific_lobbying_issues
lobbyist_filename_prefix: ccs_lda_lobbyists_additional_terms_3
output_filename_prefix: ccs_lda_filings_additional_terms_3
search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_additional_terms_3.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_additional_terms_2.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_bills_with_ccs_terms2.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_additional_terms.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_billnos_1.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_billnos_2.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_billnos_3.yml
#search_term_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/search_term_list_more_laws.yml
postproc_specs_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/ccs_postproc_specifications.yml
subset_to_ccs_only: True
law_list_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/ccs_laws.yml
organization_name_handling_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/organization_name_handling.yml
sector_description_file: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/sector_descriptions.yml
company_name_replacements: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/company_name_replacements.yml
clean_client_description_col: clean_client_general_description
company_rename_col: client_rename
company_sector_assignments: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/sectors_updated.yml
path_to_lumped_sector_info: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/lumped_sectors.yml
political_party_congress_path: /Users/lindseygulden/dev/leg-up-private/projects/lobbying/party_control_congress.yml
remove_sector_name: REMOVE
remove_org_key:
  - remove these organizations
  - keep
groupby_columns:
  - filing_year
  - filing_period
  - client_id
  - registrant_id
  - activity_id
# ********** sectors that directly profit from the sale or combustion of fossil fuels *********
core_ff_sectors:
  - oil and gas
  - investor owned utilities
  - chemicals, refining, and plastics
  - coal
  - energy technology
  - ccs
  - independent power producers
  - pipelines
  - municipal and cooperative utilities
  - oilfield services
  - clean hydrogen
  # ********** sectors that profit (direcctly or indirectly) from the sale or combustion of    *********
  # ********** fossil fuels or that are closely tied to the industry (e.g., business advocacy) *********
ff_adjacent_sectors:
  - oil and gas
  - investor owned utilities
  - chemicals, refining, and plastics
  - coal
  - biofuels
  - energy technology
  - ccs
  - independent power producers
  - air transit
  - railway
  - pipelines
  - municipal and cooperative utilities
  - business advocacy
  #- fuel cell
  - land transit
  - oilfield services
  #- carbon
  - clean hydrogen
subset_and_order_of_writeout_columns: # does not include entity binary column names: programmatically added to end
  - filing_uuid
  - total_number_lobbying_activities
  - total_number_of_lobbyists_on_filing
  - activity_id
  - n_lobbyists_for_activity
  - filing_year
  - filing_period
  - filing_dt_posted
  - which_congress
  - party_controlling_house
  - party_controlling_senate
  - party_controlling_white_house
  - filing_type
  - client_id
  - client_rename
  - client_name
  - client_general_description
  - sector
  - lumped_sector
  - very_lumped_sector
  - definitely_ccs
  - very_likely_ccs
  - likely_ccs
  - potentially_ccs
  - not_ccs
  - registrant_id
  - who_is_lobbying
  - dollars_spent_lobbying
  - lobbying_activity_usd
  - n_entities_lobbied
  - legistlative_entities_lobbied
  - executive_entities_lobbied
  - affiliated_organizations_present
  - general_issue_code
  - description
  - posted_by_name
  - registrant_name
  - registrant_contact_name
  - client_state
  - client_ppb_state
  - client_country
  - client_ppb_country
  - url
  - entity_expanded
  - clean_description
  - clean_client_general_description
  - ccs_description
  - count_ccs_description
  - clean_h2_description
  - count_clean_h2_description
  - ccs_company
  - clean_hydrogen_company
  - green_hydrogen_company
  - h2_mention_core_ff
  - h2_mention_ff_adjacent
  - ccs_bills
  - bills_with_some_ccs
  - count_bills_with_some_ccs
  - bills_with_ccs_terms
  - ccs_bills_number_only
  - terms_consistent_with_ccs
  - terms_could_be_ccs
  - ccs_because_of_who_says_it
rename_columns:
  dollars_spent_lobbying: usd_for_all_activities_on_filing_document
  client_name: client_name_on_filing_document
  client_rename: organization
  clean_client_general_description: cleaned_client_general_description
  clean_description: cleaned_description
  entity_expanded: entities_lobbied
  description: description_on_filing
  client_general_description: client_general_description_on_filing
