from utils.io import dict_to_yaml

sectors = {
    "auto and transportation": [
        "CENTER FOR TRANSPORTATION AND ENVIRONMENT",
        "HONDA",
        "TOYOTA",
        "GENERAL MOTORS",
    ],
    "iron and steel": ["ARCH RESOURCES"],
    "oil and gas": [
        "NEXEN",
        "KP KAUFFMAN",
        "DENBURY",
        "BP AMERICA",
        "SHELL",
        "CHEVRON",
        "EXXON",
        "EQUINOR US OPERATIONS",
        "SANDRIDGE ENERGY",
        "OCCIDENTAL PETROLEUM",
        "AMERICAN PETROLEUM INSTITUTE",
        "AMERICAN ASSOCIATION OF PETROLEUM GEOLOGISTS",
        "GLENROCK PETROLEUM",
        "INDEPENDENT PETROLEUM ASSOCIATION OF AMERICA",
        "AMERICAN GAS ASSOCIATION",
        "TITAN OIL RECOVERY",
        "INTERSTATE NATURAL GAS ASSOCIATION OF AMERICA",
        "INTERSTATE OIL AND GAS COMPACT COMMISSION",
        "TOTAL",
    ],
    "chemicals": [
        "AMERICAN CHEMISTRY COUNCIL",
        "AIR PRODUCTS AND CHEMICALS",
        "EASTMAN CHEMICAL",
        "LYONDELL CHEMICAL",
        "SIGNA CHEMISTRY",
        "AMERICAN FUEL PETROCHEMICAL MANUFACTURERS",
        "SOLVAY CHEMICALS",
        "DOW",
        "BAYER",
    ],
    "oilfield services": ["MM ENERGY", "MILESTONE ENVIRONMENTAL", "BAKER HUGHES"],
    "finance": [],
    "local government": [
        "STATE OF INDIANA",
        "STATE OF INDIANA OFFICE OF GOVERNOR",
        "STATE OF LOUISIANA",
    ],
    "coal": ["PEABODY", "CLINE RESOURCES", "SASOL"],
    "power generation and utilities": [
        "AMERICAN ELECTRIC POWER",
        "NRG-RRI-MIRANT-GENON",
        "DUKE",
        "ALGONQUIN POWER UTILITIES",
        "GENERATORS FOR CLEAN AIR GCA COALITION",
        "NORTHWESTERN ENERGY",
        "HOLLAND BOARD OF PUBLIC WORKS",
        "UIL-AVANGRID",
        "SOUTHERN",
        "EDISON ELECTRIC INSTITUTE",
        "FLORIDA MUNICIPAL ELECTRIC ASSOC",
        "NEXTERA",
        "PORTLAND GENERAL ELECTRIC",
        "IP RENEWABLE ENERGY HOLDINGS",
        "CLECO POWER",
        "NATIONAL GRID",
        "DTE ENERGY",
        "WASHINGTON GAS LIGHT",
        "BASIN ELECTRIC POWER COOPERATIVE",
        "AMERICAN ELECTRIC POWER",
        "OHIO MUNICIPAL ELECTRIC ASSOCIATION",
        "INTERNATIONAL BROTHERHOOD OF ELECTRICAL WORKERS",
        "NATIONAL RURAL ELECTRIC COOPERATIVE ASSOCIATION",
        "SOUTHERN MONTANA ELECTRIC GENERATION TRANSMISSION COOPERATIVE",
        "ELECTRIC POWER SUPPLY ASSOCIATION",
        "EMPIRE DISTRICT ELECTRIC",
        "PACIFIC GAS AND ELECTRIC",
        "PORTLAND GENERAL ELECTRIC",
        "FLORIDA MUNICIPAL ELECTRIC ASSOC",
        "INSTITUTE OF ELECTRICAL AND ELECTRONICS ENGINEERS",
    ],
    "food and agriculture": ["NATIONAL MILK PRODUCERS FEDERATION", "DEERE"],
    "environmental": [
        "ENVIRONMENTAL DEFENSE ACTION FUND",
        "CLEAN AIR TASK FORCE",
        "SIERRA CLUB",
        "NATIONAL PARKS CONSERVATION ASSOCIATION",
        "CITIZENS CLIMATE LOBBY",
        "CENTER FOR CLIMATE AND ENERGY SOLUTIONS",
    ],
    "higher education": [
        "UNIVERSITY OF OKLAHOMA",
        "COLORADO STATE UNIVERSITY FOUNDATION",
        "NEW MEXICO STATE UNIVERSITY",
        "UNIVERSITY OF ILLINOIS",
        "UNIVERSITY OF WYOMING",
        "RICE UNIVERSITY",
        "OHIO UNIVERSITY",
        "CARNEGIE MELLON UNIVERSITY",
        "UNIVERSITY OF NORTH DAKOTA",
        "UNIVERSITY OF PITTSBURGH",
        "UNIVERSITY OF KENTUCKY",
        "ARIZONA STATE UNIVERSITY",
        "UNIVERSITY OF TOLEDO",
        "UNIVERSITY OF OKLAHOMA",
        "UNIVERSITY OF MICHIGAN",
        "UNIVERSITY OF WASHINGTON",
        "YALE UNIVERSITY",
        "VANDERBILT UNIVERSITY",
        "GEORGIA INSTITUTE OF TECHNOLOGY",
        "MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
        "IOWA STATE UNIVERSITY",
        "UNIVERSITY OF TEXAS AT AUSTIN",
        "UNIVERSITY OF CALIFORNIA",
        "CALIFORNIA INSTITUTE OF TECHNOLOGY",
    ],
    "renewable energy": ["AMERICAN WIND ENERGY ASSOCIATION", "VINEYARD WIND"],
    "pipelines": [
        "ASSOCIATION OF OIL PIPE LINES",
        "LIQUID ENERGY PIPELINE ASSOCIATION",
        "UNITED ASSN OF JOURNEYMEN APPRENTICES OF PLUMBING PIPEFITTING INDUSTRY",
        "AMERICAN CONCRETE PRESSURE PIPE ASSOCIATION",
    ],
    "carbon management services": [],
    "paper products": [],
    "railway": [],
    "chamber of commerce": [],
    "green hydrogen": [],
    "clean hydrogen": [],
    "independent research organization": [],
    "mining": [],
    "engineering consulting": [],
    "cement": [],
}

sectors_merge2 = {
    "auto and transportation": [
        "AEROJET ROCKETDYNE",
        "UNITED AIRLINES",
        "HYUNDAI MOTOR",
        "DELTA AIR LINES",
        "CATERPILLAR",
        "NIKOLA",
    ],
    "iron and steel": [],
    "oil and gas": [
        "AMERICAS NATURAL GAS ALLIANCE",
        "CALIFORNIA RESOURCES",
        "WOODSIDE ENERGY",
        "BAYOTECH",
    ],
    "chemicals": [
        "ARKEMA",
        "CODEXIS",
        "CF INDUSTRIES",
        "BLOOM ENERGY",
        "ALTERNATIVE FUELS CHEMICALS COALITION",
        "COVANTA ENERGY",
        "ECOLAB-NALCO",
    ],
    "oilfield services": [],
    "finance": ["ARCLIGHT CAPITAL PARTNERS", "COBANK ACB"],
    "local government": [
        "SACRAMENTO MUNICIPAL UTILITY DISTRICT",
        "JAMESTOWN BOARD OF PUBLIC UTILITIES",
        "MIDLAND COUNTY TEXAS",
        "WYOMING INFRASTRUCTURE AUTHORITY",
        "COLORADO SPRINGS UTILITIES",
    ],
    "coal": [
        "C4I COALITION",
        "AMERICAN COALITION FOR CLEAN COAL ELECTRICITY",
        "COALTEK",
    ],
    "power generation and utilities": [
        "ENTERGY",
        "EDISON INTERNATIONAL",
        "TECO",
        "PNM RESOURCES",
        "NPPD",
        "PRAXAIR",
    ],
    "food and agriculture": ["INDIGO AGRICULTURE", "ALABAMA FARMERS FEDERATION"],
    "environmental": [
        "NATIONAL WILDLIFE FEDERATION",
        "FRIENDS OF EARTH",
        "LEAGUE OF CONSERVATION VOTERS",
        "NATIONAL AUDUBON SOCIETY",
        "OCEAN CONSERVANCY",
        "PLASTIC POLLUTION COALITION",
    ],
    "higher education": [],
    "renewable energy": [
        "GREEN HYDROGEN",
        "OBSIDIAN RENEWABLES",
        "ENERGY ADVANCE CENTER",
        "RENEWABLE FUELS ASSOCIATION",
    ],
    "pipelines": [],
    "carbon management services": [
        "CARBONFREE",
        "NORTH AMERICAN CARBON CAPTURE STORAGE ASSOCIATION NACCSA",
        "SKYONIC",
    ],
    "paper products": ["AMERICAN FOREST PAPER ASSOCIATION", "WEYERHAEUSER"],
    "railway": ["ASSOCIATION OF AMERICAN RAILROADS", "BNSF RAILWAY"],
    "chamber of commerce": [],
    "green hydrogen": ["HYPERION RESOURCES", "CALERA"],
    "clean hydrogen": [
        "JUPITER OXYGEN",
        "NEXTDECADE",
        "ENERGY INNOVATION REFORM PROJECT",
    ],
    "independent research organization": [
        "SCIENCE APPLICATIONS INTERNATIONAL",
        "WESTERN RESEARCH INSTITUTE",
        "IHS",
    ],
    "mining": ["NATIONAL MINING ASSOCIATION", "JOY GLOBAL"],
    "engineering consulting": [
        "STOLAR RESEARCH",
        "DES NORSKE VERITAS CLASSIFICATION AMERICAS",
    ],
    "cement": ["CALPORTLAND", "HOLCIM", "PORTLAND CEMENT ASSOCIATION"],
}

sectors_merge = {
    "cement": [],
    "auto and transportation": [],
    "iron and steel": [
        "ARCELORMITTAL",
        "NUCOR",
        "UNITED STATES STEEL",
        "SSAB ENTERPRISES",
        "CLEVELANDCLIFFS",
    ],
    "oil and gas": [
        "SHELL",
        "OCCIDENTAL PETROLEUM",
        "EXXON",
        "BP AMERICA",
        "CHEVRON",
        "MARATHON-TESORO",
        "CONOCOPHILLIPS",
        "ENI US OPERATING CO",
        "TOTAL",
        "VALERO ENERGY",
        "ENBRIDGE US",
        "TARGA RESOURCES",
        "ONEOK",
        "PHILLIPS 66",
        "ZURICH",
        "SPECTRA ENERGY",
        "CHESAPEAKE ENERGY",
        "EOG RESOURCES",
        "SANDRIDGE ENERGY",
        "GULF COAST SEQUESTRATION",
        "NEW FORTRESS ENERGY",
        "GLENROCK PETROLEUM",
        "INDEPENDENT PETROLEUM ASSOCIATION OF AMERICA",
    ],
    "chemicals": [
        "AIR PRODUCTS AND CHEMICALS",
        "COVESTRO",
        "BASF",
        "LYONDELL CHEMICAL",
        "EVONIK",
        "DOW",
        "CHEMMOD",
        "CHEMOURS",
        "FMC",
        "SOLVAY AMERICA",
        "EASTMAN CHEMICAL",
        "DUPONT DE NEMOURS",
        "BAYER",
        "SIGNA CHEMISTRY",
        "CELANESE",
        "ALKALINE WATER COMPANY",
        "POLYONE",
        "REC SILICON",
    ],
    "oilfield services": ["BAKER HUGHES", "HALLIBURTON"],
    "finance": [
        "BANK OF AMERICA",
        "BERKSHIRE HATHAWAY ENERGY",
        "ZURICH",
        "MACQUARIE INFRASTRUCTURE AND REAL ASSETS",
    ],
    "local government": [
        "STATE OF INDIANA",
        "CITY OF PORTLAND OR",
        "CITY UTILITIES OF SPRINGFIELD",
        "STATE OF LOUISIANA",
        "DOUGLAS COUNTY PUBLIC UTILITY DISTRICT",
        "TACOMA PUBLIC UTILITIES",
    ],
    "coal": [
        "PEABODY",
        "ALPHA NATURAL RESOURCES",
        "CLOUD PEAK ENERGY RESOURCES",
        "ARCH RESOURCES",
        "CONSOL ENERGY",
        "WESTMORELAND COAL",
        "BITUMINOUS COAL OPERATORS ASSOCIATION",
        "FOUNDATION COAL",
        "COAL OPERATORS AND ASSOCIATES",
        "MOUNTAINEER CLEAN COAL TECHNOLOGY",
        "SYNCOAL SOLUTIONS",
    ],
    "power generation and utilities": [
        "CMS ENERGY",
        "DUKE",
        "EXELON-CONSTELLATION-PEPCO",
        "NRG-RRI-MIRANT-GENON",
        "FIRSTENERGY",
        "NV ENERGY",
        "AMERICAN ELECTRIC POWER",
        "CENTERPOINT ENERGY",
        "PPL",
        "PUBLIC SERVICE ENTERPRISE",
        "SOUTHERN",
        "CALPINE",
        "AMEREN",
        "BLACK HILLS",
        "PORTLAND GENERAL ELECTRIC",
        "VISTRA",
        "PUGET SOUND ENERGY",
        "CLECO POWER",
        "GREAT PLAINS ENERGY",
        "XCEL ENERGY",
        "ENEL",
        "ENERGY FUTURE HOLDINGS",
        "ALLETE-ENERGYFORWARD",
        "SEMPRA",
        "WEC ENERGY",
        "ALLEGHENY ENERGY",
        "CALPINE",
        "TACOMA PUBLIC UTILITIES",
        "LIGNITE ENERGY COUNCIL",
        "GREAT PLAINS INSTITUTE",
        "MDU RESOURCES",
        "ENERGYCITY OF AUSTIN TEXAS",
        "IP RENEWABLE ENERGY HOLDINGS",
        "SALT RIVER PROJECT",
        "SOUTHERN CALIFORNIA PUBLIC POWER AUTHORITY",
        "GREEN PLAINS",
        "SOUTHERN MONTANA ELECTRIC GENERATION TRANSMISSION COOPERATIVE",
        "NORTHERN CALIFORNIA POWER AGENCY",
        "ENERGEN RESOURCES",
    ],
    "food and agriculture": [
        "ARCHER DANIELS MIDLAND",
        "TYSON FOODS",
        "POET",
        "GREEN PLAINS",
        "CORN REFINERS ASSOCIATION",
        "NATIONAL MILK PRODUCERS FEDERATION",
        "FARMERS EDUCATIONAL COOPERATIVE UNION OF AMERICA",
    ],
    "environmental": [
        "CLEAN AIR TASK FORCE",
        "SIERRA CLUB",
        "EARTHJUSTICE",
        "NATURE CONSERVANCY",
        "WORLD WILDLIFE FUND",
        "CLEAN ENERGY SYSTEMS",
        "CENTER FOR CLIMATE AND ENERGY SOLUTIONS",
        "BACKCOUNTRY HUNTERS ANGLERS",
        "GREENPEACE",
        "PUBLIC POWER COUNCIL",
        "ALGAE BIOMASS ORGANIZATION",
        "AMERICAN CLEAN POWER ASSOCIATION",
        "WILDERNESS SOCIETY",
        "BIOMASS POWER ASSOCIATION",
        "NATURE CONSERVANCY",
    ],
    "higher education": [
        "UNIVERSITY OF PITTSBURGH",
        "UNIVERSITY OF TOLEDO",
        "UNIVERSITY OF MICHIGAN",
        "UNIVERSITY OF ILLINOIS",
        "UNIVERSITY OF CALIFORNIA",
        "ARIZONA STATE UNIVERSITY",
        "IOWA STATE UNIVERSITY",
        "COLORADO STATE UNIVERSITY FOUNDATION",
        "YALE UNIVERSITY",
        "VANDERBILT UNIVERSITY",
        "UNIVERSITY OF WYOMING",
        "UNIVERSITY OF NORTH DAKOTA",
        "CALIFORNIA INSTITUTE OF TECHNOLOGY",
        "CARNEGIE MELLON UNIVERSITY",
        "MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
        "NEW MEXICO STATE UNIVERSITY",
        "OHIO UNIVERSITY",
        "UNIVERSITY OF TEXAS AT AUSTIN",
        "RICE UNIVERSITY",
    ],
    "renewable energy": [
        "NEXTERA",
        "VINEYARD WIND",
        "ACCELERGY",
        "GREEN RENEWABLE ENERGY",
        "AMERICAN WIND ENERGY ASSOCIATION",
        "VELOCYS",
        "MODERN HYDROGEN",
        "BLUE SOURCE",
        "SUNLIGHTEN",
        "ENERGYCITY OF AUSTIN TEXAS",
        "NATURAL STATE RENEWABLES",
        "SOLAMERICA ENERGY",
        "SOLAR CITY",
    ],
    "pipelines": [
        "ENBRIDGE US",
        "KINDER MORGAN CO2",
        "ASSOCIATION OF OIL PIPE LINES",
        "TARGA RESOURCES",
        "TRANSCANADA-TC ENERGY",
        "SPECTRA ENERGY",
        "CHEVRON PIPELINE",
    ],
    "carbon management services": [
        "CARBON UTILIZATION RESEARCH COUNCIL",
        "CARBON GEOCAPTURE",
        "HEIRLOOM CARBON TECHNOLOGIES",
        "CARBON ADVOCACY PROJECT",
        "CARBON ENGINEERING",
        "CCUS COALITION",
        "CARBON SINK",
        "ZERO CARBON HYDROGEN COALITION",
    ],
    "paper products": [
        "INTERNATIONAL PAPER",
        "UNITED STEEL PAPER FORESTRY RUBBER MANUFACTURING ENERGY",
    ],
    "railway": [
        "NORFOLK SOUTHERN",
        "UNION PACIFIC",
        "CANADIAN PACIFIC RAILWAY",
        "CSX",
        "AMERICAN ASSOCIATION OF PORT AUTHORITIES",
    ],
    "chamber of commerce": [
        "NATIONAL ASSOCIATION OF MANUFACTURERS",
        "US CHAMBER OF COMMERCE",
        "GREATER PITTSBURGH CHAMBER OF COMMERCE",
    ],
    "green hydrogen": [
        "UNIVERSAL HYDROGEN",
        "INVENTYS-SVANTE",
        "ALGENOL",
        "Q HYDROGEN",
        "BLUE GREEN ALLIANCE",
    ],
    "clean hydrogen": [
        "PLUG POWER",
        "HYDROGEN ENERGY CALIFORNIA HECA",
        "NEXTEA CLEAN HYDROGEN",
        "TWELVE BENEFIT",
    ],
    "independent research organization": [
        "BATTELLE",
        "RTI INTERNATIONAL",
        "IDDRI",
        "GDF SUEZ ENERGY",
        "BLUE SOURCE",
    ],
    "mining": [
        "RIO TINTO",
        "BHP",
        "TALON NICKEL",
        "DRUMMOND",
        "COOK INLET REGION",
        "MILESTONE ENVIRONMENTAL",
    ],
    "engineering consulting": ["WSP", "BLACK VEATCH", "DNV GL", "EPRI", "AECOM"],
}

sectors_merge3 = {
    "pipelines": [],
    "cement": [],
    "food and agriculture": [],
    "auto and transportation": [
        "AMERICAN PUBLIC TRANSPORTATION ASSOCIATION",
        "CUMMINS",
    ],
    "iron and steel": ["METALS"],
    "oil and gas": [
        "WMPI PTY",
        "TELLUS OPERATING",
        "WILLIAMS COMPANIES",
        "NATIONAL OCEAN INDUSTRIES ASSOCIATION",
        "CNX RESOURCES",
        "BAKKEN ENERGY",
        "EQT",
        "HEIMDAL",
    ],
    "chemicals": [
        "METHANOL INSTITUTE",
        "LINDE",
        "RENTECH",
        "LAKE CHARLES METHANOL",
        "AIR LIQUIDE",
        "HNO INTERNATIONAL",
    ],
    "oilfield services": ["TETRA TECHNOLOGIES"],
    "finance": [
        "PINNACLE WEST CAPITAL",
        "ARTHUR J GALLAGHER",
        "NATIONAL VENTURE CAPITAL ASSOCIATION",
        "BIXBYATLANTIC",
        "CLARK STREET ASSOCIATES",
        "LEUCADIA NATIONAL",
        "LIEBMAN ASSOCIATES",
        "COLIBRI ENTERPRISES",
        "BCE",
        "ARA ADVISERS PSG",
    ],
    "local government": [
        "CENTRAL ARIZONA WATER CONSERVATION DISTRICT",
        "AUSTIN ENERGYCITY OF AUSTIN TEXAS",
        "PORT OF CORPUS CHRISTI AUTHORITY OF NUECES COUNTY TEXAS",
    ],
    "coal": ["CLEAN COAL TECHNOLOGIES", "WESTERN FUELS"],
    "power generation and utilities": [
        "CINERGY",
        "THERMOENERGY",
        "POWERSPAN",
        "THAYER GATE ENERGY",
        "NUCLEAR ENERGY INSTITUTE",
        "LARGE PUBLIC POWER COUNCIL",
        "WOLVERINE POWER COOPERATIVE",
        "DINE POWER AUTHORITY",
        "RAMGEN POWER SYSTEMS",
        "AMERICAS POWER",
        "EXCELSIOR ENERGY",
        "AMERICAN PUBLIC POWER ASSOCIATION",
        "PROGRESS ENERGY",
        "AMERICAN TRANSMISSION",
        "MISSOURI RIVER ENERGY",
        "INDUSTRIAL ENERGY CONSUMERS OF AMERICA",
        "JADOO POWER SYSTEMS",
        "ENYRGY",
        "TRISTATE GENERATION AND TRANSMISSION ASSOCIATION",
        "SOAP CREEK ENERGY",
        "ENGIE",
        "PRAIRIE STATE GENERATING",
        "DRAX",
        "NET POWER",
    ],
    "environmental": [
        "ENVIRES",
        "NATIONAL GROUND WATER ASSOCIATION",
        "AMERICAN LUNG ASSOCIATION",
        "WASTE MANAGEMENT",
        "NATIONAL ALLIANCE OF FOREST OWNERS",
        "FOOD WATER WATCH",
        "REWORLD WASTE",
        "GROUND WATER PROTECTION COUNCIL",
        "PATAGONIA",
        "ADVANTEK WASTE MANAGEMENT",
    ],
    "higher education": [],
    "renewable energy": [
        "NEW GENERATIONS BIOFUELS",
        "USA BIOMASS POWER PRODUCERS ALLIANCE",
        "CLEARPATH ACTION FOR CONSERVATIVE CLEAN ENERGY",
        "CORE ENERGY",
        "BUSINESS COUNCIL FOR SUSTAINABLE ENERGY",
        "GROWTH ENERGY",
        "CLEAN ENERGY",
        "CEMVITA FACTORY",
        "HIGHLY INNOVATIVE FUELS",
        "BLUE SKY INFRASTRUCTURE",
        "AMERICAN BIOGAS COUNCIL",
        "AMERICAN BIOMASS ENERGY ASSOCIATION",
        "US BIOCHAR COALITION",
        "BIAENERGY OPERATING",
    ],
    "carbon management services": [
        "ADA CARBON SOLUTIONS",
        "CCS ALLIANCE",
        "VERUTEK TECHNOLOGIES",
        "ENVIROGENX",
        "CHARM INDUSTRIAL",
        "CZERO",
        "NAVIGATOR CO2",
        "PROJECT VESTA",
        "LITHOS CARBON",
        "H CYCLE",
        "CATF ACTION",
        "REMORA",
    ],
    "paper products": ["AMERICAN WOOD COUNCIL", "GLASS PACKAGING INSTITUTE GPI"],
    "railway": [],
    "chamber of commerce": [
        "BUSINESS COUNCIL OF ALABAMA",
        "NATIONAL ASSOCIATION OF TOWER ERECTORS",
        "BUSINESS ROUNDTABLE",
        "WESTERN BUSINESS ROUNDTABLE",
        "ASSOCIATED BUILDERS AND CONTRACTORS",
        "NATSO",
    ],
    "green hydrogen": ["CLEAN HYDROGEN FUTURE COALITION"],
    "clean hydrogen": [
        "GREATPOINT ENERGY",
        "LANZATECH",
        "HUDSON CLEAN ENERGY PARTNERS",
        "LIBERTY-QURATE",
        "MONOLITH MATERIALS",
        "CALIX",
        "FUEL CELL AND HYDROGEN ENERGY ASSOCIATION",
        "HYDROGEN FUEL CELL BUS COUNCIL",
    ],
    "independent research organization": [
        "BIOTECHNOLOGY INNOVATION ORGANIZATION",
        "XPRIZE FOUNDATION",
        "NANO TERRA",
    ],
    "mining": ["ALUMINUM ASSOCIATION", "FORTESCUE", "GLENCORE"],
    "engineering consulting": [
        "GE-ALSTOM",
        "BABCOCK WILCOX",
        "PROCESS ENERGY SOLUTIONS",
        "BWX TECHNOLOGIES",
        "AKERMIN",
        "LENNOX INTERNATIONAL",
        "SIEMENS",
        "GEODIGITAL INTERNATIONAL",
        "ASPEN AEROGELS",
        "ASSOCIATED EQUIPMENT DISTRIBUTORS",
        "CHICAGO BRIDGE IRON N V",
        "WARTSILA",
        "HONEYWELL INTERNATIONAL",
        "MITSUBISHI",
        "DRESSER RAND",
        "SCHNEIDER ELECTRIC",
        "ROBERT BOSCH",
        "TOPSOE",
        "LEIDOS",
        "ASME",
    ],
}

sectors_merge4 = {
    "auto and transportation": ["TRANSPORTATION COMMUNICATIONS NATIONAL UNIONIAM"],
    "iron and steel": [
        "INTL ASSOCIATION OF BRIDGE STRUCTURAL ORNAMENTAL REINFORCING IRON WORKERS",
        "UNITED STEELWORKERS",
    ],
    "oil and gas": [
        "MAGELLAN MIDSTREAM PARTNERS",
        "TARGA RESOURCES PARTNERS",
        "HOWARD ENERGY PARTNERS",
        "CROWLEY MARITIME",
        "KEURIG DR PEPPER",
        "WABASH VALLEY RESOURCES",
        "MINNKOTA POWER COOPERATIVE",
        "BRIMSTONE ENERGY",
    ],
    "chemicals": [
        "CEMEX",
        "INVENTYS THERMAL TECHNOLOGIES DBA INVENTYS-SVANTE",
        "FERTILIZER INSTITUTE",
        "CHART INDUSTRIES",
        "VERDE CO2",
        "ORIGIN MATERIALS",
        "REPUBLIC",
        "SUNTORY GLOBAL SPIRITS",
    ],
    "oilfield services": [],
    "finance": [
        "AMERICANS FOR TAX REFORM",
        "CENTER FOR AMERICAN PROGRESS ACTION FUND",
        "BIPARTISAN POLICY CENTER ACTION",
        "WILEY REIN",
        "AFLCIO",
        "DORSEY WHITNEY",
    ],
    "local government": [],
    "coal": ["CLEAN COAL TECHNOLOGIES", "MJBA COALITIONS"],
    "power generation and utilities": [
        "TENASKA",
        "EVERSOURCE ENERGY SERVICE",
        "FOSTER WHEELER",
        "DOMINION",
        "COUNCIL OF INDUSTRIAL BOILER OWNERS",
        "SITHE GLOBAL POWER",
        "NEW YORK ASSOCIATION OF PUBLIC POWER",
        "SUMMIT POWER",
        "DKRW ENERGY",
        "ENERGY INDUSTRIES OF OHIO",
        "AMERICAN MUNICIPAL POWER",
        "UNITED BIOREFINERIES",
        "FUTUREGEN INDUSTRIAL ALLIANCE",
        "NATIONAL FUEL GAS",
        "MINNKOTA POWER COOPERATIVE",
    ],
    "environmental": [
        "NATIONAL WASTE RECYCLING ASSOCIATION",
        "CITIZENS FOR RESPONSIBLE ENERGY SOLUTIONS",
        "AMERICAN FOREST FOUNDATION",
        "GROWTH ENERGY",
        "FOOD WATER WATCH",
        "GROUND WATER PROTECTION COUNCIL",
        "REWORLD WASTE",
    ],
    "higher education": [],
    "renewable energy": [
        "BREAKTHROUGH ENERGY",
        "NUCLEAR INNOVATION ALLIANCE",
        "NET NEGATIVE CO2 BASELOAD POWER",
        "PROJECT CANARY",
        "TALLGRASS",
        "ORSTED",
        "CALSTART",
        "USA BIOMASS POWER PRODUCERS ALLIANCE",
        "CLEARPATH ACTION FOR CONSERVATIVE CLEAN ENERGY",
        "AMERICAN BIOGAS COUNCIL",
        "AMERICAN BIOMASS ENERGY ASSOCIATION",
        "US BIOCHAR COALITION",
    ],
    "carbon management services": [
        "CEMVITA",
        "ADA CARBON SOLUTIONS",
        "CCS ALLIANCE",
        "ENVIROGENX",
        "CHARM INDUSTRIAL",
        "CZERO",
        "NAVIGATOR CO2",
        "PROJECT VESTA",
        "LITHOS CARBON",
        "H CYCLE",
        "CATF ACTION",
        "REMORA",
    ],
    "paper products": ["AMERICAN WOOD COUNCIL", "GLASS PACKAGING INSTITUTE GPI"],
    "railway": [],
    "chamber of commerce": [
        "BUILDING AND CONSTRUCTION TRADES DEPARTMENT AFLCIO",
        "AMERICAN FED OF GOVERNMENT EMPLOYEES AFLCIO",
        "INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL TRANSPORTATION WORKERS",
        "INTL ASSN OF SHEET METAL AIR RAIL TRANSP WORKERS TRANSP DIV",
        "CENTER FOR INDIVIDUAL FREEDOM",
        "AMERICAN CONSERVATIVE UNION",
        "ASSOCIATED BUILDERS AND CONTRACTORS",
        "NATSO",
    ],
    "green hydrogen": ["CLEAN HYDROGEN FUTURE COALITION"],
    "clean hydrogen": [
        "BREAKTHROUGH ENERGY",
        "HUDSON CLEAN ENERGY PARTNERS",
        "BRIMSTONE ENERGY",
        "VERDE CO2",
        "ORSTED",
    ],
    "independent research organization": [
        "XPRIZE FOUNDATION",
        "BIOTECHNOLOGY INNOVATION ORGANIZATION",
        "NANO TERRA",
    ],
    "mining": [],
    "engineering consulting": [
        "ESCRUB SYSTEMS",
        "GE-ALSTOM",
        "FOSTER WHEELER",
        "SITHE GLOBAL POWER",
        "ENERGY INDUSTRIES OF OHIO",
        "ORBITAL ATK",
        "BLEDSOE ASSOCIATES",
        "HITACHI ENERGY",
        "MICROSOFT",
        "CHART INDUSTRIES",
        "TOPSOE",
        "LEIDOS",
        "ASME",
    ],
    "food and agriculture": [],
    "pipelines": [],
    "cement": [],
}
sector5 = {}
for s in sectors.keys():
    sector5[s] = []
sector5 = sector5 | {
    "chamber of commerce": [
        "LABORERS INTERNATIONAL UNION OF",
        "UNITED BROTHERHOOD OF CARPENTERS AND JOINERS OF AMERICA",
        "INTERNATIONAL UNION OF PAINTERS AND ALLIED TRADES",
        "INTERNATIONAL UNION OF OPERATING ENGINEERS",
        "UNITED MINE WORKERS OF AMERICA",
        "INTERNATIONAL BROTHERHOOD OF BOILERMAKERS",
        "INTERNATIONAL BROTHERHOOD OF TEAMSTERS",
        "WORLD SHIPPING COUNCIL",
    ],
    "independent research organization": [
        "NC12",
        "INNOVATION REFORM ACTION PROJECT",
        "TAXPAYERS FOR COMMON SENSE",
        "LTC ACTION",
    ],
    "food and agriculture": ["UNILEVER UNITED STATES", "NEW YORK FARM BUREAU"],
    "renewable energy": ["COMBINED HEAT AND POWER ALLIANCE"],
    "coal": ["CLEAN ENERGY STRATEGYMJBA COALITIONS"],
    "oil and gas": ["WORLD ENERGY"],
    "carbon management services": ["DIFFERENTIATED GAS COORDINATING COUNCIL COALITION"],
}

sector_assignments = {}
for s in sectors_merge2.keys():
    sector_assignments[s] = list(
        set(sectors[s])
        | set(sectors_merge[s])
        | set(sectors_merge2[s])
        | set(sectors_merge3[s])
        | set(sectors_merge4[s])
        | set(sector5[s])
    )

dict_to_yaml(sector_assignments, "projects/lobbying/sectors.yml")
