auto and transportation:
- HONDA
- HYDROGEN FUEL CELL BUS COUNCIL
- AEROJET ROCKETDYNE
- NIKOLA
- CUMMINS
- GENERAL MOTORS
- UNITED AIRLINES
- TOYOTA
- DELTA AIR LINES
- AMERICAN PUBLIC TRANSPORTATION ASSOCIATION
- CATERPILLAR
- CENTER FOR TRANSPORTATION AND ENVIRONMENT
- HYUNDAI MOTOR
- CROWLEY MARITIME
- BLOOM ENERGY
- INTERNATIONAL BROTHERHOOD OF TEAMSTERS
- MAERSK AGENCY
carbon management services:
- CEMVITA FACTORY
- NET NEGATIVE CO2 BASELOAD POWER
- US BIOCHAR COALITION
- INVENTYS-SVANTE
- GULF COAST SEQUESTRATION
- ADVANTEK WASTE MANAGEMENT
- VERDE CO2
- CARBON ENGINEERING
- HEIMDAL
- BLUE SOURCE
- SKYONIC
- H CYCLE
- REMORA
- CHARM INDUSTRIAL
- CARBON SINK
- CARBON GEOCAPTURE
- ENVIROGENX
- CARBON UTILIZATION RESEARCH COUNCIL
- LITHOS CARBON
- NAVIGATOR CO2
- NORTH AMERICAN CARBON CAPTURE STORAGE ASSOCIATION NACCSA
- CEMVITA
- HEIRLOOM CARBON TECHNOLOGIES
- ZERO CARBON HYDROGEN COALITION
- CCS ALLIANCE
- CCUS COALITION
- CARBONFREE
- ADA CARBON SOLUTIONS
- PROJECT VESTA
cement:
- PORTLAND CEMENT ASSOCIATION
- HOLCIM
- CALPORTLAND
- CEMEX
- BRIMSTONE ENERGY
business advocacy:
- NATIONAL ASSOCIATION OF MANUFACTURERS
- NATIONAL ASSOCIATION OF TOWER ERECTORS
- INTERNATIONAL BROTHERHOOD OF BOILERMAKERS
- WESTERN BUSINESS ROUNDTABLE
- BUSINESS COUNCIL OF ALABAMA
- INTERNATIONAL UNION OF PAINTERS AND ALLIED TRADES
- ASSOCIATED BUILDERS AND CONTRACTORS
- INTERNATIONAL UNION OF OPERATING ENGINEERS
- BUILDING AND CONSTRUCTION TRADES DEPARTMENT AFLCIO
- AMERICAN CONSERVATIVE UNION
- BUSINESS ROUNDTABLE
- WORLD SHIPPING COUNCIL
- GREATER PITTSBURGH CHAMBER OF COMMERCE
- UNITED BROTHERHOOD OF CARPENTERS AND JOINERS OF AMERICA
- LABORERS INTERNATIONAL UNION OF
- CENTER FOR INDIVIDUAL FREEDOM
- NATSO
- INTL ASSN OF SHEET METAL AIR RAIL TRANSP WORKERS TRANSP DIV
- US CHAMBER OF COMMERCE
chemicals:
- EASTMAN CHEMICAL
- SASOL
- AMERICAN FUEL PETROCHEMICAL MANUFACTURERS
- DOW
- ARKEMA
- POLYONE
- BASF
- AMERICAN CHEMISTRY COUNCIL
- LYONDELL CHEMICAL
- AIR PRODUCTS AND CHEMICALS
- SIGNA CHEMISTRY
- CHEMMOD
- ORIGIN MATERIALS
- SOLVAY CHEMICALS
- CF INDUSTRIES
- ALKALINE WATER COMPANY
- ALTERNATIVE FUELS CHEMICALS COALITION
- METHANOL INSTITUTE
- RENTECH
- REC SILICON
- FERTILIZER INSTITUTE
- CHEMOURS
- AIR LIQUIDE
- COVESTRO
- SOLVAY AMERICA
- DUPONT DE NEMOURS
- CELANESE
- ECOLAB-NALCO
- LINDE
- CODEXIS
- FMC
- CHART INDUSTRIES
- BAYER
- LAKE CHARLES METHANOL
- EVONIK
clean hydrogen:
- ACCELERGY
- TWELVE BENEFIT
- PLUG POWER
- HYPERION RESOURCES
- NEXTEA CLEAN HYDROGEN
- BAYOTECH
- FUEL CELL AND HYDROGEN ENERGY ASSOCIATION
- HYDROGEN ENERGY CALIFORNIA HECA
- MONOLITH MATERIALS
- JUPITER OXYGEN
- NEXTDECADE
- GREATPOINT ENERGY
- PRAXAIR
- CZERO
coal:
- LIGNITE ENERGY COUNCIL
- AMERICAS POWER
- ARCH RESOURCES
- FUTUREGEN INDUSTRIAL ALLIANCE
- WMPI PTY
- DRUMMOND
- GENERATORS FOR CLEAN AIR GCA COALITION
- COAL OPERATORS AND ASSOCIATES
- PEABODY
- WESTMORELAND COAL
- COALTEK
- AMERICAN COALITION FOR CLEAN COAL ELECTRICITY
- CLOUD PEAK ENERGY RESOURCES
- ALPHA NATURAL RESOURCES
- WESTERN FUELS
- SYNCOAL SOLUTIONS
- MOUNTAINEER CLEAN COAL TECHNOLOGY
- CLINE RESOURCES
- CONSOL ENERGY
- BITUMINOUS COAL OPERATORS ASSOCIATION
- FOUNDATION COAL
- CLEAN COAL TECHNOLOGIES
- C4I COALITION
engineering consulting:
- COLIBRI ENTERPRISES
- MICROSOFT
- EPRI
- MITSUBISHI
- HITACHI ENERGY
- ESCRUB SYSTEMS
- DRESSER RAND
- BABCOCK WILCOX
- BLACK VEATCH
- PROCESS ENERGY SOLUTIONS
- BWX TECHNOLOGIES
- ASPEN AEROGELS
- ROBERT BOSCH
- AKERMIN
- LEIDOS
- BLEDSOE ASSOCIATES
- ORBITAL ATK
- DNV GL
- CHICAGO BRIDGE IRON N V
- DES NORSKE VERITAS CLASSIFICATION AMERICAS
- SCHNEIDER ELECTRIC
- SIEMENS
- ASSOCIATED EQUIPMENT DISTRIBUTORS
- LENNOX INTERNATIONAL
- GEODIGITAL INTERNATIONAL
- WSP
- ASME
- FOSTER WHEELER
- WARTSILA
- AECOM
- HONEYWELL INTERNATIONAL
- TOPSOE
- GE-ALSTOM
- STOLAR RESEARCH
environmental:
- CARBON ADVOCACY PROJECT
- LTC ACTION
- ENERGY INNOVATION REFORM PROJECT
- MJBA COALITIONS
- NATIONAL PARKS CONSERVATION ASSOCIATION
- NATIONAL WASTE RECYCLING ASSOCIATION
- EARTHJUSTICE
- GROUND WATER PROTECTION COUNCIL
- CITIZENS CLIMATE LOBBY
- FOOD WATER WATCH
- GREENPEACE
- PLASTIC POLLUTION COALITION
- PATAGONIA
- NATIONAL ALLIANCE OF FOREST OWNERS
- AMERICAN LUNG ASSOCIATION
- SIERRA CLUB
- REWORLD WASTE
- LEAGUE OF CONSERVATION VOTERS
- FRIENDS OF EARTH
- NATIONAL AUDUBON SOCIETY
- WILDERNESS SOCIETY
- OCEAN CONSERVANCY
- CITIZENS FOR RESPONSIBLE ENERGY SOLUTIONS
- ENVIRES
- ENVIRONMENTAL DEFENSE ACTION FUND
- CENTER FOR CLIMATE AND ENERGY SOLUTIONS
- AMERICAN FOREST FOUNDATION
- BACKCOUNTRY HUNTERS ANGLERS
- CLEAN AIR TASK FORCE
- WORLD WILDLIFE FUND
- ALGAE BIOMASS ORGANIZATION
- NATIONAL WILDLIFE FEDERATION
- CLEAN ENERGY SYSTEMS
- NATIONAL GROUND WATER ASSOCIATION
- NATURE CONSERVANCY
other:
- AFLCIO
- LIBERTY-QURATE
finance:
- BREAKTHROUGH ENERGY
- CLARK STREET ASSOCIATES
- LEUCADIA NATIONAL
- BCE
- HUDSON CLEAN ENERGY PARTNERS
- ARCLIGHT CAPITAL PARTNERS
- WILEY REIN
- DORSEY WHITNEY
- PINNACLE WEST CAPITAL
- COBANK ACB
- LIEBMAN ASSOCIATES
- ARA ADVISERS PSG
- ZURICH
- BANK OF AMERICA
- MACQUARIE INFRASTRUCTURE AND REAL ASSETS
- BERKSHIRE HATHAWAY ENERGY
- NATIONAL VENTURE CAPITAL ASSOCIATION
- ARTHUR J GALLAGHER
biofuels:
- AMERICAN BIOMASS ENERGY ASSOCIATION
- AMERICAN BIOGAS COUNCIL
- USA BIOMASS POWER PRODUCERS ALLIANCE
- GROWTH ENERGY
- GREEN PLAINS
- UNITED BIOREFINERIES
- NEW GENERATIONS BIOFUELS
- BIOMASS POWER ASSOCIATION
- COVANTA ENERGY
- BIAENERGY OPERATING
- POET
- CORN REFINERS ASSOCIATION
food and agriculture:
- FARMERS EDUCATIONAL COOPERATIVE UNION OF AMERICA
- SUNTORY GLOBAL SPIRITS
- UNILEVER UNITED STATES
- INDIGO AGRICULTURE
- LANZATECH
- NATIONAL MILK PRODUCERS FEDERATION
- ALABAMA FARMERS FEDERATION
- TYSON FOODS
- KEURIG DR PEPPER
- ARCHER DANIELS MIDLAND
- NEW YORK FARM BUREAU
- DEERE
green hydrogen:
- HNO INTERNATIONAL
- BLUE GREEN ALLIANCE
- CALERA
- UNIVERSAL HYDROGEN
- ALGENOL
- Q HYDROGEN
- CLEAN HYDROGEN FUTURE COALITION
- HIGHLY INNOVATIVE FUELS
- MODERN HYDROGEN
- VELOCYS
- GREEN HYDROGEN
higher education:
- UNIVERSITY OF MICHIGAN
- VANDERBILT UNIVERSITY
- UNIVERSITY OF TEXAS AT AUSTIN
- COLORADO STATE UNIVERSITY FOUNDATION
- YALE UNIVERSITY
- ARIZONA STATE UNIVERSITY
- UNIVERSITY OF TOLEDO
- OHIO UNIVERSITY
- NEW MEXICO STATE UNIVERSITY
- UNIVERSITY OF ILLINOIS
- UNIVERSITY OF CALIFORNIA
- UNIVERSITY OF WASHINGTON
- MASSACHUSETTS INSTITUTE OF TECHNOLOGY
- RICE UNIVERSITY
- CALIFORNIA INSTITUTE OF TECHNOLOGY
- UNIVERSITY OF NORTH DAKOTA
- IOWA STATE UNIVERSITY
- UNIVERSITY OF KENTUCKY
- UNIVERSITY OF PITTSBURGH
- UNIVERSITY OF WYOMING
- UNIVERSITY OF OKLAHOMA
- GEORGIA INSTITUTE OF TECHNOLOGY
- CARNEGIE MELLON UNIVERSITY
independent research organization:
- NC12
- ENERGY INDUSTRIES OF OHIO
- GREAT PLAINS INSTITUTE
- INNOVATION REFORM ACTION PROJECT
- SCIENCE APPLICATIONS INTERNATIONAL
- IDDRI
- RTI INTERNATIONAL
- IHS
- XPRIZE FOUNDATION
- BIOTECHNOLOGY INNOVATION ORGANIZATION
- NANO TERRA
- WESTERN RESEARCH INSTITUTE
- BATTELLE
iron and steel:
- SSAB ENTERPRISES
- UNITED STEELWORKERS
- NUCOR
- CALIX
- UNITED STATES STEEL
- CLEVELANDCLIFFS
- ARCELORMITTAL
- INTL ASSOCIATION OF BRIDGE STRUCTURAL ORNAMENTAL REINFORCING IRON WORKERS
government:
- CITY OF PORTLAND OR
- STATE OF INDIANA
- INTERSTATE OIL AND GAS COMPACT COMMISSION
- AMERICAN FED OF GOVERNMENT EMPLOYEES AFLCIO
- WYOMING INFRASTRUCTURE AUTHORITY
- STATE OF INDIANA OFFICE OF GOVERNOR
- PORT OF CORPUS CHRISTI AUTHORITY OF NUECES COUNTY TEXAS
- STATE OF LOUISIANA
- CENTRAL ARIZONA WATER CONSERVATION DISTRICT
- MIDLAND COUNTY TEXAS
- TAXPAYERS FOR COMMON SENSE
- AMERICANS FOR TAX REFORM
- CENTER FOR AMERICAN PROGRESS ACTION FUND
- BIPARTISAN POLICY CENTER ACTION
mining:
- ALUMINUM ASSOCIATION
- NATIONAL MINING ASSOCIATION
- JOY GLOBAL
- FORTESCUE
- TALON NICKEL
- BHP
- METALS
- RIO TINTO
- UNITED MINE WORKERS OF AMERICA
oil and gas:
- CLEARPATH ACTION FOR CONSERVATIVE CLEAN ENERGY
- ENERGEN RESOURCES
- DIFFERENTIATED GAS COORDINATING COUNCIL COALITION
- COOK INLET REGION
- EQUINOR US OPERATIONS
- WABASH VALLEY RESOURCES
- MAGELLAN MIDSTREAM PARTNERS
- CNX RESOURCES
- TITAN OIL RECOVERY
- TELLUS OPERATING
- DENBURY
- NEXEN
- GLENCORE
- SHELL
- HOWARD ENERGY PARTNERS
- TOTAL
- MARATHON-TESORO
- BAKKEN ENERGY
- AMERICAS NATURAL GAS ALLIANCE
- CHEVRON
- ENI US OPERATING CO
- VALERO ENERGY
- EQT
- CHESAPEAKE ENERGY
- WILLIAMS COMPANIES
- PHILLIPS 66
- GLENROCK PETROLEUM
- OCCIDENTAL PETROLEUM
- KP KAUFFMAN
- ONEOK
- EOG RESOURCES
- BP AMERICA
- AMERICAN GAS ASSOCIATION
- NEW FORTRESS ENERGY
- NATIONAL OCEAN INDUSTRIES ASSOCIATION
- SANDRIDGE ENERGY
- AMERICAN ASSOCIATION OF PETROLEUM GEOLOGISTS
- CONOCOPHILLIPS
- TARGA
- WOODSIDE ENERGY
- EXXON
- WORLD ENERGY
- INTERSTATE NATURAL GAS ASSOCIATION OF AMERICA
- CALIFORNIA RESOURCES
- INDEPENDENT PETROLEUM ASSOCIATION OF AMERICA
- AMERICAN PETROLEUM INSTITUTE
oilfield services:
- VERUTEK TECHNOLOGIES
- HALLIBURTON
- TETRA TECHNOLOGIES
- BAKER HUGHES
- MM ENERGY
- MILESTONE ENVIRONMENTAL
- BIXBYATLANTIC
- REPUBLIC
- WASTE MANAGEMENT
paper products:
- WEYERHAEUSER
- GLASS PACKAGING INSTITUTE GPI
- AMERICAN FOREST PAPER ASSOCIATION
- INTERNATIONAL PAPER
- AMERICAN WOOD COUNCIL
- UNITED STEEL PAPER FORESTRY RUBBER MANUFACTURING ENERGY
pipelines:
- CHEVRON PIPELINE
- COMPRESSED GAS ASSOCIATION
- ASSOCIATION OF OIL PIPE LINES
- TRANSCANADA-TC ENERGY
- LIQUID ENERGY PIPELINE ASSOCIATION
- KINDER MORGAN CO2
- AMERICAN CONCRETE PRESSURE PIPE ASSOCIATION
- SPECTRA-ENBRIDGE
- UNITED ASSN OF JOURNEYMEN APPRENTICES OF PLUMBING PIPEFITTING INDUSTRY
power generation and utilities:
- AUSTIN ENERGY
- PUBLIC POWER COUNCIL
- SACRAMENTO MUNICIPAL UTILITY DISTRICT
- JAMESTOWN BOARD OF PUBLIC UTILITIES
- COLORADO SPRINGS UTILITIES
- CITY UTILITIES OF SPRINGFIELD
- TACOMA PUBLIC UTILITIES
- DOUGLAS COUNTY PUBLIC UTILITY DISTRICT
- INTERNATIONAL BROTHERHOOD OF ELECTRICAL WORKERS
- TENASKA
- CALPINE
- SOUTHERN CALIFORNIA PUBLIC POWER AUTHORITY
- NEW YORK ASSOCIATION OF PUBLIC POWER
- GREAT PLAINS ENERGY
- MISSOURI RIVER ENERGY
- WASHINGTON GAS LIGHT
- CINERGY
- EXELON-CONSTELLATION-PEPCO
- NATIONAL FUEL GAS
- FIRSTENERGY
- NATIONAL GRID
- EXCELSIOR ENERGY
- EDISON INTERNATIONAL
- EDISON ELECTRIC INSTITUTE
- ALLEGHENY ENERGY
- INDUSTRIAL ENERGY CONSUMERS OF AMERICA
- NET POWER
- NRG-RRI-MIRANT-GENON
- PNM RESOURCES
- PORTLAND GENERAL ELECTRIC
- ENEL
- EMPIRE DISTRICT ELECTRIC
- POWERSPAN
- BASIN ELECTRIC POWER COOPERATIVE
- AMEREN
- SOAP CREEK ENERGY
- AMERICAN MUNICIPAL POWER
- THERMOENERGY
- SUMMIT POWER
- HOLLAND BOARD OF PUBLIC WORKS
- ENERGY FUTURE HOLDINGS
- AMERICAN TRANSMISSION
- NATIONAL RURAL ELECTRIC COOPERATIVE ASSOCIATION
- CLECO POWER
- SALT RIVER PROJECT
- SOUTHERN MONTANA ELECTRIC GENERATION TRANSMISSION COOPERATIVE
- COUNCIL OF INDUSTRIAL BOILER OWNERS
- PROGRESS ENERGY
- MDU RESOURCES
- VISTRA
- NEXTERA
- NUCLEAR ENERGY INSTITUTE
- DINE POWER AUTHORITY
- BLACK HILLS
- DOMINION
- CMS ENERGY
- DRAX
- RAMGEN POWER SYSTEMS
- SITHE GLOBAL POWER
- WEC ENERGY
- TRISTATE GENERATION AND TRANSMISSION ASSOCIATION
- NV ENERGY
- AMERICAN PUBLIC POWER ASSOCIATION
- DTE ENERGY
- PACIFIC GAS AND ELECTRIC
- CENTERPOINT ENERGY
- NORTHWESTERN ENERGY
- AMERICAN ELECTRIC POWER
- WOLVERINE POWER COOPERATIVE
- SEMPRA
- EVERSOURCE ENERGY SERVICE
- TECO
- MINNKOTA POWER COOPERATIVE
- NPPD
- OHIO MUNICIPAL ELECTRIC ASSOCIATION
- PUGET SOUND ENERGY
- ALGONQUIN POWER UTILITIES
- DUKE
- INSTITUTE OF ELECTRICAL AND ELECTRONICS ENGINEERS
- NORTHERN CALIFORNIA POWER AGENCY
- UIL-AVANGRID
- PPL
- JADOO POWER SYSTEMS
- ENYRGY
- ENGIE
- ELECTRIC POWER SUPPLY ASSOCIATION
- XCEL ENERGY
- ALLETE-ENERGYFORWARD
- THAYER GATE ENERGY
- DKRW ENERGY
- SOUTHERN
- ENTERGY
- PUBLIC SERVICE ENTERPRISE
- FLORIDA MUNICIPAL ELECTRIC ASSOC
- LARGE PUBLIC POWER COUNCIL
- PRAIRIE STATE GENERATING
railway:
- NORFOLK SOUTHERN
- UNION PACIFIC
- BNSF RAILWAY
- ASSOCIATION OF AMERICAN RAILROADS
- AMERICAN ASSOCIATION OF PORT AUTHORITIES
- CSX
- CANADIAN PACIFIC RAILWAY
- TRANSPORTATION COMMUNICATIONS NATIONAL UNIONIAM
- INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL TRANSPORTATION WORKERS
renewable energy:
- ORSTED
- AMERICAN CLEAN POWER ASSOCIATION
- RENEWABLE FUELS ASSOCIATION
- IP RENEWABLE ENERGY HOLDINGS
- OBSIDIAN RENEWABLES
- BLUE SKY INFRASTRUCTURE
- SOLAR CITY
- COMBINED HEAT AND POWER ALLIANCE
- AMERICAN WIND ENERGY ASSOCIATION
- CALSTART
- SUNLIGHTEN
- ENERGY ADVANCE CENTER
- PROJECT CANARY
- TALLGRASS
- SOLAMERICA ENERGY
- GREEN RENEWABLE ENERGY
- CORE ENERGY
- NUCLEAR INNOVATION ALLIANCE
- BUSINESS COUNCIL FOR SUSTAINABLE ENERGY
- CLEAN ENERGY
- NATURAL STATE RENEWABLES
- VINEYARD WIND