DewPointC: dew_point_c
DewPointF: dew_point_f
FeelsLikeC: feels_like_c
FeelsLikeF: feels_like_f
HeatIndexC: heat_index_c
HeatIndexF: heat_index_f
WindChillC: wind_chill_c
WindChillF: wind_chill_f
WindGustKmph: wind_gust_kmph
WindGustMiles: wind_gust_mph
avgtempC: avg_temp_c
avgtempF: avg_temp_f
cloudcover: cloud_cover
date: date
humidity: humidity
maxtempC: max_temp_c
maxtempF: max_temp_f
mintempC: min_temp_c
mintempF: min_temp_f
moon_illumination: moon_illumination
moon_phase: moon_phase
moonrise: moonrise_local_time
moonset: moonset_local_time
precipInches: precip_in
precipMM: precip_mm
pressure: pressure_mb
pressureInches: pressure_in
sunHour: sun_hour
sunrise: sunrise_local_time
sunset: sunset_local_time
tempC: temp_c
tempF: temp_f
time: time
totalSnow_cm: total_snow_cm
uvIndex: uv_index
visibility: visibility_km
visibilityMiles: visibility_mi
weatherCode: weather_code
weatherDesc: weather_desc
winddir16Point: wind_dir_16_point
winddirDegree: wind_dir_degree
windspeedKmph: windspeed_kmph
windspeedMiles: windspeed_mph