# Yaml config file for real-world simulations of UES as part of RHG CCS analysis
# June 2024
#
# -- paths
path_to_brent_data: /Volumes/Samsung_T5/data/oilgas/brent_oil_prices_2023_dollars.csv
path_to_breakeven_data: /Volumes/Samsung_T5/data/ccs/breakeven_triangular_distribution_parameters_2023_usd_per_bbl.csv
path_to_cost_data: /Volumes/Samsung_T5/data/ccs/ccs_costs_by_industry.csv
output_path: /Volumes/Samsung_T5/data/ccs/ues_simulations.csv
brent_since_yrs:
- 1987
- 2014
discount_rate: 0.12
# scalar by which to multiply transport and storage cost prices for obtaining 'right' side of triangular distribution
high_end_scalar: 1.25
industries:
- NG Processing
- Ethanol
- Ammonia
- Hydrogen
- Cement
- Refinery
- Iron/Steel
- Ethylene
inflation_rate: 0.025
# scalar by which to multiply transport and storage cost prices for obtaining 'left' side of triangular distribution
low_end_scalar: 0.75
nsamples: 2000 # number of ensemble members
project_length_yrs: 15
scenario_name: realistic simulations for testing ccs profitability
tco2_sequestered_per_yr:
- 0
- 0
- 0
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
well_types:
- existing
- new
