# yaml configuration file specifying assumptions used in unit economics simulator to represent the
# three different Rhodium Group 'emissions pathway' scenarios
output_dir: /Volumes/Samsung_T5/data/ccs_economics/
costs_file: /Volumes/Samsung_T5/data/ccs_economics/ccs_costs_by_industry.csv
rhg_2040_projections_file: /Volumes/Samsung_T5/data/ccs_economics/rhodium_2024_projected_total_installed_ccs_capacity_in_2040.csv
discount_rate: 0.12
high_inflation_rate: 0.021
high_price_scalar: 1.25
low_inflation_rate: 0.017
low_price_scalar: 0.75
oil_breakeven_price: 30
project_length_yrs: 15
rhg_oil_cases_file: /Volumes/Samsung_T5/data/ccs_economics/rhg_oil_price_cases_brent_crude_2023_usd.csv
tco2_sequestered_per_yr:
- 0
- 0
- 0
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
