# this file contains data for the rooftop solar comparison
solar_kwh_data_file: /Volumes/Samsung_T5/data/ccs/6kw_solar_npc_states_3tilts_9azimuths.csv
time_varying_carbon_intensity_file: /Volumes/Samsung_T5/data/ccs/us_fossil_fuel_carbon_intensity_projections.csv
output_file: /Volumes/Samsung_T5/data/ccs/comparison_case_for_solar.csv
# pick from 'avg_install_usd','low_install_usd', and 'high_install_usd'
which_install_scenario: 'avg_install_usd'
inflation_rate: 0.025
discount_rate: 0.12
bond_interest_rate: 0.0428
project_length_yrs: 25

