# Yaml file containing local paths to CCS industry locations
#
# ----- Industry facility location data sources (obtained June 2024) -----
# subparts: https://www.epa.gov/ghgreporting/resources-subpart-ghg-reporting
# Cement data obtained here: https://datadryad.org/stash/dataset/doi:10.5061/dryad.6t1g1jx4f
# Ethanol data obtained here: https://atlas.eia.gov/datasets/3f984029aadc4647ac4025675799af90/explore
# NGP data obtained here: https://atlas.eia.gov/datasets/eia::natural-gas-processing-plants/about
# Ethylene crackers data obtained here: https://atlas.eia.gov/datasets/2a3894eae1df438fab70d6f6f0a8867f_253/explore?location=36.450742%2C-92.906029%2C6.85
# Petroleum refineries data obtained here: https://atlas.eia.gov/datasets/6547eda91ef84cc386e23397cf834524_22/explore?location=0.006192%2C-116.156875%2C0.00
# Ammonia plants data obtained here: https://nutrien-prod-asset.s3.us-east-2.amazonaws.com/s3fs-public/uploads/2023-11/Nutrien_2023Fact%20Book_Update_112723.pdf
# Note that ammonia data referenced originally by https://www.statista.com/statistics/1266392/ammonia-plant-capacities-united-states/
#
# ----- Assumed storage-region centroids were specified by placing a single lat-lon point in the approximate
# visual center of the five storage regions in figure 2-9 of Chapter 2 of the National Petroleum Council's
# CCS report: https://dualchallenge.npc.org/files/CCUS-Chap_2-030521.pdf
#
#
# Path to file with EPA's summary data table from the FLIGHT database
epa_flight_summary_data: "/Users/lindseygulden/Downloads/epa_flight_2022_co2.csv"
# NOTE -- for epa_flight_abbr dict, important that double letters come first
epa_flight_abbr:
  AA: pulp and paper
  C: general combustion
  DD: electric transmission
  D: power plant
  FF: underground coal mines
  F: aluminum
  G: ammonia
  H: cement
  J: ethanol
  MM: petroleum products
  NN: natural gas and ngls
  PP: co2_supplier
  P: hydrogen
  Q: iron_steel
  S: lime manufacturing
  TT: industrial waste landfills
  V: nitric acid
  W: natural gas processing
  X: petrochemicals
  Y: refineries
eia_refineries: "/Volumes/Samsung_T5/data/ccs/Petroleum_Refineries_US_EIA_-2313742254698534431.geojson"
ethylene: "/Volumes/Samsung_T5/data/ccs/Ethylene_Crackers_US_EIA_-6819071495948750171.geojson"
ethanol: "/Volumes/Samsung_T5/data/ccs/Ethanol_Plants_US_EIA_4402532010393384397.geojson"
ngp: "/Volumes/Samsung_T5/data/ccs/NaturalGas_ProcessingPlants_US_EIA_6278090561902649650.geojson"
ammonia: "/Volumes/Samsung_T5/data/ccs/ammonia.csv"
cement: "/Volumes/Samsung_T5/data/ccs/cement.csv"
# storage region location and cost information (from NPC report)
npc_storage_region_info: "/Volumes/Samsung_T5/data/ccs/npc_storage_regions_representative_points.csv"
# capture information, computed with GaffneyCline's cash flow model and modified assumptions
capture_excel_file: "/Users/lindseygulden/dev/leg-up/projects/ccs/gaffney_cline_assumptions_and_modified_assumptions.xlsx"
capture_assumptions_sheet_name: "modified_assumptions"
capture_unit_cost_row_name: "Total Capture Cost (US$/tonne)"
industries:
  - ngp
  - ethanol
  - ammonia
  - hydrogen
  - cement
  - refinery
  - steel
  - industrial
  #- coal_power_85pct
  #- ng_power_85pct
