# Yaml config file to keep parameters for real-world simulations of UES June 2024
#
# -- paths
path_to_brent_data: /Volumes/Samsung_T5/data/oilgas/brent_oil_prices_2023_dollars.csv
path_to_breakeven_data: /Volumes/Samsung_T5/data/ccs/breakeven_triangular_distribution_parameters_2023_usd_per_bbl.csv
path_to_cost_data: /Volumes/Samsung_T5/data/ccs/ccs_costs_by_industry.csv
output_path: /Volumes/Samsung_T5/data/ccs/ues_simulations.csv
brent_since_yrs:
- 1987
- 2014
discount_rate: 0.12
high_end_scalar: 1.25
industries:
- NG Processing
- Ethanol
- Ammonia
- Hydrogen
- Cement
- Refinery
- Iron/Steel
- Ethylene
inflation_rate: 0.025
low_end_scalar: 0.75
nsamples: 2000
project_length_yrs: 15
scenario_name: realistic simulations for testing ccs profitability
tco2_sequestered_per_yr:
- 0
- 0
- 0
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
well_types:
- existing
- new
