# This configuration YAML provides information for querying the World Weather Online local history API
# See https://www.worldweatheronline.com/ for more information and to obtain an API key
locations: # list of strings that are either US Zipcode, UK Postcode, Canada Postalcode, IP address, Latitude/Longitude (decimal degree) or city name
   - '02459'
api_key: "cbcffe5648e04b07afa203548241202"  # API key obtained from https://www.worldweatheronline.com/
entry_point: "https://api.worldweatheronline.com/premium/v1/past-weather.ashx"  # not expecting this to change...but you never know
start_date : "01-JAN-2020"  # date when desired period starts; format: 'dd-MMM-yyyy', e.g., '01-JAN-2020'
end_date : "31-DEC-2022"  # date when desired period ends;  format: 'dd-MMM-yyyy,  e.g., '01-JAN-2020'
timeout_seconds: 30 #number of seconds after which to time out the request to the WWO API
frequency : 24  # number of hours spanned by observations: possible values 1 (1 hour), 3 (3 hours), 6 (6 hours), 12 (12 hours (day/night)) or 24 (daily averages)
forecast_vars:
   - 'date'
   - 'maxtempF'
   - 'mintempF'
   - 'avgtempF'
   - 'maxtempC'
   - 'mintempC'
   - 'avgtempC'
   - 'totalSnow_cm'
   - 'sunHour'
   - 'uvIndex'
weather_vars:
   - 'time'
   - 'tempC'
   - 'tempF'
   - 'windspeedMiles'
   - 'windspeedKmph'
   - 'winddirDegree'
   - 'winddir16Point'
   - 'weatherCode'
   - 'weatherDesc'
   - 'precipMM'
   - 'precipInches'
   - 'humidity'
   - 'visibility'
   - 'visibilityMiles'
   - 'pressure'
   - 'pressureInches'
   - 'cloudcover'
   - 'HeatIndexC'
   - 'HeatIndexF'
   - 'DewPointC'
   - 'DewPointF'
   - 'WindChillC'
   - 'WindChillF'
   - 'WindGustMiles'
   - 'WindGustKmph'
   - 'FeelsLikeC'
   - 'FeelsLikeF'
   - 'uvIndex'
   - 'date'
   - 'maxtempF'
   - 'mintempF'
   - 'avgtempF'
   - 'totalSnow_cm'
   - 'sunHour'
